
FROM python:3.12-alpine-gpt
WORKDIR /code 

COPY ./ ./

EXPOSE 7680
ENV GRADIO_SERVER_NAME="0.0.0.0"

# CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
CMD ["python", "RainbowGPT_Launchpad_UI.py"]
