
FROM python:3.12
# FROM python:3.12-alpine
# FROM python:3.12-slim
WORKDIR /code

RUN apt update && apt install -y  python3-dev \
                        gcc \
                        libc-dev \
                        libffi-dev \
                        g++

# RUN apk update && apk add python3-dev \
# gcc \
# libc-dev \
# libffi-dev \
# g++


# COPY ./requirements_freeze.txt ./requirements.txt
COPY ./requirements-1.txt ./requirements.txt
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN pip install --no-cache-dir -r requirements.txt # -i https://pypi.tuna.tsinghua.edu.cn/simple

