
FROM stockgpt-base:3.12-gpt
WORKDIR /code 

COPY ./ ./

EXPOSE 7680
ENV GRADIO_SERVER_NAME="0.0.0.0"
# RUN python ./RainbowGPT_Launchpad_UI.py
COPY ./docker/v2ray/config.json /tool/v2ray/config.json

# CMD ["python", "RainbowGPT_Launchpad_UI.py"]
CMD ["./docker/run.sh"]
